name: Build

on:
  push:
  pull_request:

#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-java@v3
#      with:
#        distribution: temurin
#        java-version: 11
#    - uses: gradle/gradle-build-action@v2
#    - name: Build
#      run: |
#        ./gradlew --info --stacktrace build reobfJar
#    - uses: actions/upload-artifact@v3
#      with:
#        name: artifacts
#        path: "**/build/libs/*.jar"
