name: Rattle
version: $version
main: ${group}.rattle.paper.PaperRattle
description: $description
api-version: 1.19
authors: [ aecsocket ]
website: https://github.com/aecsocket/rattle
# TODO Folia
#folia-supported: true
