name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - uses: gradle/gradle-build-action@v2
      - name: Run Gradle build
        run: |
          ./gradlew build reobfJar
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: "**/libs/*.jar"
