name: Ignacio
version: $version
main: ${group}.ignacio.paper.Ignacio
description: $description
api-version: 1.19
authors: [ aecsocket ]
website: https://github.com/aecsocket/ignacio
folia-supported: true
