# Config file for Ignacio
# Example file is available at
# https://github.com/aecsocket/ignacio/blob/main/ignacio-paper/src/main/resources/settings.yml

# The default locale to use for the plugin. Must be a valid Java locale.
# string: en-US
default-locale: en-US

# Settings for physics spaces which are linked to game worlds.
worlds:
  # Physics space initialization parameters.
  space:
    # The gravity vector - acceleration to apply to all moving bodies. (m/s^2)
    # 3D decimal vector: [ 0.0, -9.81, 0.0 ]
    gravity: [ 0.0, -9.81, 0.0 ]
  # Multiplier for the physics time step - decreasing will make the simulation slower (slow-motion).
  # decimal: 1.0
  delta-time-multiplier: 1.0
  # Which method to use for managing bodies for block terrain.
  # (none, moving_slice): moving_slice
  terrain-strategy: moving_slice
  # Settings for the moving_slice terrain strategy.
  terrain-strategy-moving-slice:
    # When calculating what terrain around a body should be calculated, an axis-aligned box is used,
    # which is based on the body's world-space coordinates.
    # This box is expanded in the direction of the body's current velocity.
    # The velocity is multiplied by this factor to determine the expansion.
    # decimal: 0.2
    bounds-expansion-velocity-factor: 0.2
    # A constant amount of padding which is added on all sides of the bounding box. (metres)
    # 3D decimal vector: [ 4.0, 4.0, 4.0 ]
    bounds-expansion-constant: [ 4.0, 4.0, 4.0 ]
    # Friction constant of the terrain body.
    # decimal: 0.5
    friction: 0.5
    # Restitution constant of the terrain body.
    # decimal: 0.1
    restitution: 0.1
  # Which method to use for managing bodies for entities.
  # (none, default): default
  entity-strategy: default

# Settings for bodies spawned with `/ignacio body create`.
primitive-bodies:
  # Item descriptors for the models of primitive shapes.
  # If you have a custom resource pack, these should be sized as unit shapes.
  # The model should span from (0, 0, 0) to (16, 16, 16) in Blockbench units.
  models:
    # For `/ignacio body create [...] box`.
    box:
      material: minecraft:stone
    # For `/ignacio body create [...] sphere`.
    sphere:
      material: minecraft:stone
  # How far a body is allowed to move before its marker entity is teleported. (metres)
  # Teleporting is a potentially expensive operation, especially on Folia.
  # decimal: 16.0
  teleport-threshold: 16.0

# Settings for timing statistics shown by `/ignacio timings`.
engine-timings:
  # How many seconds of timings to keep in the buffer.
  # decimal: 60.0
  buffer: 60.0
  # Which intervals to display timings data for in `/ignacio timings`.
  # decimal list: [ 5.0, 15.0, 60.0 ]
  buffers-to-display: [ 5.0, 15.0, 60.0 ]
  # How many seconds of the timings buffer to display for in the `/ignacio debug --show-timings` bar.
  # decimal: 5.0
  bar-buffer: 5.0
  # How the bar from `/ignacio debug --show-timings` should be displayed.
  bar:
    progress: 1.0
    color: white
    overlay: progress

# Settings for the Jolt engine internals.
# You should probably leave this alone, unless you know what you're doing.
jolt:
  jobs:
    physics-threads: 0
    worker-threads: 0
    thread-terminate-time: 5.0
    max-jobs: 2048
    max-barriers: 8
  space:
    max-bodies: 65536
    num-body-mutexes: 0
    max-body-pairs: 65536
    max-contact-constraints: 16384
    temp-allocator-size: 33554432 # 32 * 1024 * 1024
    collision-steps: 1
    integration-sub-steps: 3 # max 4
  physics:
    max-in-flight-body-pairs: 16384
    step-listeners-batch-size: 8
    step-listener-batches-per-job: 1
    baumgarte: 0.2
    speculative-contact-distance: 0.02
    penetration-slop: 0.02
    linear-cast-threshold: 0.75
    linear-cast-max-penetration: 0.25
    manifold-tolerance-sq: 0.0000001 # 1.0e-6f
    max-penetration-distance: 0.2
    body-pair-cache-max-delta-position-sq: 0.00001 # 0.001f * 0.001f
    body-pair-cache-cos-max-delta-rotation-div-2: 0.9998476951563913 # cos(radians(2.0f) / 2.0f)
    contact-normal-cos-max-delta-rotation: 0.9961946980917455 # cos(radians(5.0f))
    contact-point-preserve-lambda-max-dist-sq: 0.001 # 0.01f * 0.01f
    num-velocity-steps: 10
    num-position-steps: 2
    min-velocity-for-restitution: 1.0
    time-before-sleep: 0.5
    point-velocity-sleep-threshold: 0.03
    constraint-warm-start: true
    use-body-pair-contact-cache: true
    use-manifold-reduction: true
    allow-sleeping: true
    check-active-edges: true
