# Example file is available at
# https://github.com/aecsocket/rattle/blob/main/rattle-common/src/main/resources/settings.toml
# Units are metres, seconds, kilograms.

# The default locale to use for the plugin. Must be a valid Java locale.
default-locale = "en-US"
# The multiplier for the physics engine update rate.
# If below 1, acts as "slow motion". If above 1, the opposite.
time-step-multiplier = 1.0

# Settings for worlds which are not explicitly defined.
# To explicitly define settings for a world:
# [worlds.'minecraft:overworld']

# World physics space settings
[worlds.default.physics]
# The constant acceleration applied to all moving rigid bodies.
gravity = [0.0, -9.81, 0.0]

# World dynamic terrain generation settings
[worlds.default.terrain]
# After all bodies leave a chunk section, how long do we wait until we
# remove that section's collision?
remove-time = 0.5

# Settings on expanding collider bounding boxes when determining chunk sections
[worlds.default.terrain.expansion]
# How much the velocity of a body affects the expansion of its bounds.
velocity-factor = 0.1
# A constant value, in metres, of how much the bound is expanded by.
constant = 4.0

# Settings for the `/rattle stats` display.
[stats]
# For which intervals we output the stats in `/rattle stats` for.
timing-buffers = [ 5.0, 15.0, 60.0 ]
# For which interval we calculate the stats in the timing stats bar.
timing-bar-buffer = 5.0
# Style of the timing stats bar.
timing-bar = { progress = 1.0, color = "white", overlay = "progress" }

[jobs]
# How many threads we allocate to the physics worker thread pool.
# If 0 or less, automatically calculates the value.
worker-threads = 0
# On server shutdown, how long we wait for the physics threads to finish,
# until we force a shutdown.
thread-terminate-time = 5.0
# When a command runs a physics task, how long we wait for the task to finish,
# until we force exit the command.
command-task-terminate-time = 5.0
