name: Publish

on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - name: Generate docs
        run: |
          ./gradlew --info --stacktrace dokkaHtmlMultiModule
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS_PAT }}
          external_repository: aecsocket/aecsocket.github.io
          publish_dir: ./build/dokka/htmlMultiModule
          destination_dir: ./rattle/dokka
